dist: bionic

language: cpp
compiler:
  - clang

git:
  depth: 1

addons:
  apt:
    sources:
      - sourceline: 'ppa:mhier/libboost-latest'
#     - sourceline: 'ubuntu-toolchain-r-test'
    packages:
      - boost1.67
      - libssl-dev
      - libmysqlclient-dev
      - libreadline6-dev
      - zlib1g-dev
      - libbz2-dev
      - g++-6

services:
  - mysql

before_install:
  - git config user.email "travis@build.bot" && git config user.name "Travis CI"
  - git tag -a -m "Travis build" init

install:
  - mysql -uroot -e 'create database test_mysql;'
  - mkdir bin
  - cd bin
  - cmake ../ -DWITH_WARNINGS=0 -DCMAKE_BUILD_TYPE=Release
  - cd ..

script:
  - $CXX --version
  - cd bin
  - make -j 4 -k && make install
